// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfYSAk-6OEzNpJUnjKFS41BeVNA7tBGRQ',
    appId: '1:529308010079:web:880425ab655434ad83bdea',
    messagingSenderId: '529308010079',
    projectId: 'ciberseguridad-6a481',
    authDomain: 'ciberseguridad-6a481.firebaseapp.com',
    storageBucket: 'ciberseguridad-6a481.firebasestorage.app',
    measurementId: 'G-E6BW7QDXVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgImn1npnhJ1jzmXXCs0o38-Gg318fjAk',
    appId: '1:529308010079:android:b74a1ce53b8b38dc83bdea',
    messagingSenderId: '529308010079',
    projectId: 'ciberseguridad-6a481',
    storageBucket: 'ciberseguridad-6a481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK7iAYS6IJwy6N0FqAsWG9t3drrhLDa9c',
    appId: '1:529308010079:ios:58a71840d6121c6383bdea',
    messagingSenderId: '529308010079',
    projectId: 'ciberseguridad-6a481',
    storageBucket: 'ciberseguridad-6a481.firebasestorage.app',
    iosBundleId: 'com.example.protectionInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK7iAYS6IJwy6N0FqAsWG9t3drrhLDa9c',
    appId: '1:529308010079:ios:58a71840d6121c6383bdea',
    messagingSenderId: '529308010079',
    projectId: 'ciberseguridad-6a481',
    storageBucket: 'ciberseguridad-6a481.firebasestorage.app',
    iosBundleId: 'com.example.protectionInformation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfYSAk-6OEzNpJUnjKFS41BeVNA7tBGRQ',
    appId: '1:529308010079:web:672987923e279b2b83bdea',
    messagingSenderId: '529308010079',
    projectId: 'ciberseguridad-6a481',
    authDomain: 'ciberseguridad-6a481.firebaseapp.com',
    storageBucket: 'ciberseguridad-6a481.firebasestorage.app',
    measurementId: 'G-RFCX22KS5M',
  );
}
